### ISSUE TITLE
[RuntimeException] The node has no label

### ISSUE THREAD

**Issue by FelikZ** [neoxygen/neo4j-neogen#15]
Using example neogen.yml from README:

```
connection:
  scheme: http
  host: localhost
  port: 7474

nodes:
  persons:
    label: Person
    count: 50
    properties:
      firstname: firstName
      lastname: lastName

  companies:
    label: Company
    count: 10
    properties:
      name: company
      description: catchPhrase

relationships:
  person_works_for:
    start: persons
    end: companies
    type: WORKS_AT
    mode: n..1

  friendships:
    start: persons
    end: persons
    type: KNOWS
    mode: n..n
```

It generates a runtime exception that "node has no label", but they actually does: 

```
$ ./bin/neogen generate --export="export.gen"

  [RuntimeException]     
  The node has no label  

generate [--export[="..."]]
```

I figured out that problem could be that nodes could have multiple `labels` so I tried to use `labels` instead of `label`, and it is probably running successfully then:

```
$ ./bin/neogen generate
0.023596048355103
```

But the problem is no matter I am specifying `--export="export.cql"` or using `connection` setting from yml file - it doesn't output anything anywhere except this times.
