### ISSUE TITLE
Yaml definition does not allow proper tree structure definition

### ISSUE THREAD

**Issue by Leward** [neoxygen/neo4j-neogen#9]
It is quite easy with the Cypher notation to define tree structure thanks to identifiers: 

```
(user:User {email:email} *5)
(user)-[:filespace *1..1]->(fs:FileSpace *5)
(fs)-[:contains *1..n]->(file:File {name: randomNumber} *10)
(fs)-[:contains *1..n]->(folder:Folder {name: randomNumber} *5)
(folder)-[:contains *1..n]->(file2:File {name: randomNumber} *10)
```

However with Yaml definition it is something else. If we take an example of something that currently as expected: 

```
connection:
  scheme: http
  host: localhost
  port: 7474

nodes:
  users:
    label: User
    count: 5
    properties:
      email: email
  fileSpaces:
      label: FileSpace
      count: 5
  files: 
      label: File
      count: 10

relationships:
  fileSpaceRels:
    start: User
    end: FileSpace
    type: FILESPACE
    mode: 1..1
  fileSpaceContainsFiles: 
    start: FileSpace
    end: File
    type: CONTAINS
    mode: 1..n
```

We see that relationships start and end nodes are described based on the label rather than on the identifier like for the Cypher Query. Adding folders in the later example should be quite easy. However, introducing files inside folder is another story as the relationship description will match files at the root and files that should be in folders at the same time. 

It is somehow possible to have a tree-like structure by cheating using new intermediate labels for nested files. But it's really messy has we cannot make clean Cypher on that tree afterward: 

```
connection:
  scheme: http
  host: localhost
  port: 7474

nodes:
  users:
    label: User
    count: 5
    properties:
      email: email
  fileSpaces:
    label: FileSpace
    count: 5
  files: 
    label: File
    count: 10
  folders: 
    label: Folder
    count: 5
  firstLvlFiles:
    label: FirstLvlFile
    count: 15

relationships:
  fileSpaceRels:
    start: User
    end: FileSpace
    type: FILESPACE
    mode: 1..1
  fileSpaceContainsFiles: 
    start: FileSpace
    end: File
    type: CONTAINS
    mode: 1..n
  fileSpaceContainsFolders: 
    start: FileSpace
    end: Folder
    type: CONTAINS
    mode: 1..n
  foldersContainsFirstLvlFiles: 
    start: Folder
    end: FirstLvlFile
    type: CONTAINS
    mode: 1..n
```
